# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 692b88ca24772f8bf244d1d745f8713ef2c163b914b9eacfa10153ca7520379e1bd09ab1b07d07caab2c7dcbd3c1023252bf70c19fe772a459b463ca4fbc074d

test:
  secret_key_base: bc27f44858430328432f7bd79b619f81eaf33aa875650f334fb52f4a2f221813c15473c709740229ab047ef45c80ccb83a68edb710faf8de27a00a473aa6043d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
